services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: focusaura-backend
    ports:
      - "8000:8000"
    environment:
      # You.com API Configuration
      - YOU_API_KEY=${YOU_API_KEY}
      - YOU_API_MODE=${YOU_API_MODE:-live}
      - YOU_API_TIMEOUT=${YOU_API_TIMEOUT:-10}
      - YOU_API_CACHE_ENABLED=${YOU_API_CACHE_ENABLED:-true}
      - YOU_API_CACHE_TTL=${YOU_API_CACHE_TTL:-300}
      - YOU_API_DEBUG=${YOU_API_DEBUG:-false}
    env_file:
      - ./backend/.env
    volumes:
      # Mount source code for development hot-reload
      - ./backend:/app
      # Exclude Python cache and virtual environments
      - /app/__pycache__
      - /app/.venv
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health', timeout=2.0)"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - focusaura-network

networks:
  focusaura-network:
    driver: bridge
